runmedev/docs.runme.dev

components/Hero.tsx, fresh.gen.ts, islands/TypeWriter.tsx, third_party/Typewriter.ts, third_party/Typewriter/constants.ts, third_party/Typewriter/utils.ts, third_party/raf.ts
=> Typewriter Effect

components/Sections.tsx
addresses https://github.com/stateful/runme.dev/issues/41
=> walkthrough youtube embded on how it works section

.github/workflows/test.yaml, tests/components.test.tsx, tests/islands.test.tsx
=> Add test pipeline for Deno unit tests

src/components/Footer.tsx, src/components/Hero.tsx, src/components/ServiceTabs.tsx, static/robots.txt
=> Minor SEO improvements

.github/dependabot.yml, .github/workflows/update.yml
This patch adds two files (`dependabot.yml` and `update.yml`) that allows us to have dependencies automatically updated (once every week), if our pipeline passes. I've been using this approach in WebdriverIO now very successfully and thought we could adapt this too.
=> Auto update project dependencies

src/css/custom.css
I'm using the main tag to decide if we're in docusaurus or not, which isn't great. I bet there's a better place for this css.
@christian-bromann
=> Colors and underline for links docusaurus pages

src/components/TypeWriter.tsx
=> Fix typewrite animation when clicking on the logo

src/css/custom.css
@mxsdev gave me an interesting hint to reproduce the issue. I am not sure if this is a good general fix for it but given it is not a common display bug it will work for now.
fixes #79
=> Fix display issue with navigation

docusaurus.config.js, package-lock.json, package.json, src/css/custom.css, src/css/mobile.css
This PR adds a doc search based on Algolia's engine.
__Work in Progess:__ I need to set up the Algolia part which is blocked, as I am waiting on their approval.
=> Add Algolia Search

docs/cli.md, docs/configuration.md, docs/examples.md, docs/features.md, docs/getting-started.md, docs/install.md, docs/intro.md, docs/open-source.md
Builds on top of https://github.com/stateful/runme.dev/pull/89.
=> Edits to get to initial release of Getting Started Guide

src/components/Footer.tsx, src/components/Sections.tsx
- update stateful company tagline
- footer revamp
=> Link to getting started

src/css/custom.css
This PR fixes an issue with the header that disappears on Scroll:
=> Fix sticky header

docs/open-source.md, docusaurus.config.js, src/components/Hero.tsx, src/components/Sections.tsx, src/pages/index.tsx
=> Runme explained

docs/configuration.md
=> Document `promptEnv`

src/css/custom.css
=> Simple font instead of Stateful's brand choice

docusaurus.config.js, package-lock.json, src/css/custom.css, src/theme/NotFound.tsx
Not sure if this little word joke lands, happy to rephrase it.
FYI: the font-family for the footer sections is not identical with the one on runme.dev. I didn't want to introduce another font-family just for this page.
=> Align 404 page with main site

docs/configuration.md
New in v1.5.1. Will merge once released.
=> New options

docs/integrations.md
unblocks https://github.com/stateful/runme.dev/pull/26
=> GitHub Action Integration documentation

docusaurus.config.js
Revert "Hide algolia until we make sure it works"
This reverts commit 1bdec13b53c86007b83c936dc0cae466b66784b6.
Work in progress, verifying if it works
=> Revive Algolia search

docs/install.md
=> runme is now in Brew core

package-lock.json, package.json, src/css/custom.css
Don't ask 🙄 no idea why Safari needs `padding` for a textarea for copy to work.
=> (fix): copy code in Safari

docs/getting-started/cli.md, docs/getting-started/index.md, docs/getting-started/vs-code.md, docs/getting-started/web.md, src/components/EnvironmentOptions.tsx, src/components/Icons.tsx
=> (docs): bring back Runme for web

docs/install.md
=> Document how to setup Runme with Docker

docs/architecture.md, docs/faq.md, docs/features.md, docs/index.md, docs/open-source.md
First stab at it @edeediong. Merging this now.
=> Rewriting docs to set stage for Runme v2 narrative

catalog-info.yaml
Doing some minor changes to the backstage catalog config
=> chore: adding backstage config

.vscode/settings.json, docs/getting-started/runbyexample.md
Don't just use `$__` but use real ENV vars to reference previous results.
=> Add explanation for shebang++

.vscode/tasks.json, README.md, docs/Reference/configuration.md, docs/configuration/cell-level.md
Adds documentation related to the automatic resolution of MIME-Types.
Related to: https://github.com/stateful/vscode-runme/pull/1390
=> Improves MIME-Type's documentation

package-lock.json, package.json
=> June 2024 deps upgrade

docs/guide/k8s/k8s-secret.md, docs/guide/k8s/kubectl.md
This PR Contains:
- Guide on using kubectl
=> docs: guide on using kubectl

LICENSE, package-lock.json, package.json, vercel.json
Regular maintenance of dependencies.
=> chore(deps): Feb 27, 2025
